name: Build the app and run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM Dependencies
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: display my SoftUni username
      run: echo "Murtadoc"

  ui_test:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Installing NPM Dependencies
      run: npm install
    - name: install playwright dependencies needed for UI tests
      run: npx playwright install
    - name: Starting the app to run UI tests
      run: npm start &
    - name: Running the UI tests
      run: npm run test:ui  

  render_deploy_cookbook:
    needs: ui_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Cookbook to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_COOKBOOK_MURTADOC }}
          api-key: ${{ secrets.MY_RENDER_API_KEY_COOKBOOK_MURTADOC }}